---
interfaces:
  access:
  - authentication-protocol: PAP
    interface: ens4
    outer-vlan: 60
    stream-group-id: 1
    vlan-mode: N:1
  network:
  - address: 180.10.10.2/30
    address-ipv6: 2010:1010:abab::a/112
    gateway: 180.10.10.1
    gateway-ipv6: 2010:1010:abab::1
    interface: ens5.10
