name: Scan Dockerfile and Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-dind
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Downcase REPO
      run: |
        echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Get Job ID
      id: get_job_id
      run: |
        curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs" \
        | jq '.jobs[] | select(.name=="scan") | .id' > job_id.txt
        echo "job_id=$(cat job_id.txt)" >> $GITHUB_OUTPUT

    - name: Check version trivy
      run: trivy version
  
    - name: Scan Dockerfile 
      id: scan_dockerfile
      run: |
        trivy config --severity HIGH,CRITICAL --format table --output dockerfile_scanning_result.json --exit-code 1 ./Dockerfile
        if [[ $? -ne 0 ]]; then
          echo "SCANNING_DOCKERFILE_FAILED=true" >> $GITHUB_OUTPUT
          echo $SCANNING_DOCKERFILE_FAILED
        fi
      continue-on-error: true
      
    - name: Send mail to committer if detect vulnerability in Dockerfile
      if: steps.scan_dockerfile.outputs.SCANNING_DOCKERFILE_FAILED
      uses: dawidd6/action-send-mail@v4
      with:
        server_address: smtp.gmail.com
        server_port: 465
        secure: true
        username: ${{vars.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: "[ALERT] Vulnerabilities Found in Dockerfile"
        body: |
          Hello ${{ github.event.head_commit.author.name }},

          Detected vulnerabilities for commit:
          ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.event.head_commit.id }}

          View the full report here:
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ steps.get_job_id.outputs.job_id }}
          
          Please review the details and take appropriate action.

          Best,
          SRE Team
        to: ${{ github.event.head_commit.author.email }}
        from: kien.kim@svtech.com.vn

    - name: Show results for Dockerfile scanning
      run: |
        echo "##[command] Show results for Dockerfile scanning"
        cat dockerfile_scanning_result.json
  
    - name: Build image
      if: always()
      run: docker build -t bngblaster-app:latest .

    - name: Scan Docker image
      if: always()
      run: trivy image --server http://10.98.7.14:7777 --severity HIGH,CRITICAL --format table --output image_scanning_result.json --exit-code 1 bngblaster-app:latest

    - name: Send mail to committer if detect vulnerability in Docker image
      if: failure()
      uses: dawidd6/action-send-mail@v4
      with:
        server_address: smtp.gmail.com
        server_port: 465
        secure: true
        username: ${{vars.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: "[ALERT] Vulnerabilities Found in Docker Image"
        body: |
          Hello ${{ github.event.head_commit.author.name }},

          Detected vulnerabilities for commit:
          ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.event.head_commit.id }}

          View the full report here:
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ steps.get_job_id.outputs.job_id }}
          
          Please review the details and take appropriate action.

          Best,
          SRE Team
        to: ${{ github.event.head_commit.author.email }}
        from: kien.kim@svtech.com.vn

    - name: Show results for Image scanning
      run: |
        echo "##[command] Show results for Image scanning"
        cat image_scanning_result.json

    - name: Upload Dockerfile scan results as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Dockerfile scanning result
        path: dockerfile_scanning_result.json
        
    - name: Upload Image scanning results as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Image scanning result
        path: image_scanning_result.json
        